[package]
name = "diffraction-factor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
egui_extras = { version = "0.32.3", features = ["all_loaders"] }
egui_plot = "0.33.0"
egui-plotter = "0.6.0"
plotters = "0.3"
fresnel = "0.1.0"
